name: DEV
variables:
  - name: CORE_WS_URL
    value: https://fm-tsv-core-ws-dev.pvu.cf.churchofjesuschrist.org/api/v2
  - name: BASE_URL
    value: https://templeworkercore-service-dev.churchofjesuschrist.org/api/v2
    disabled: true
  - name: TEMPLE_ORG_ID
    value: "5001001"
  - name: WORKER1_ID
    value: "9104"
  - name: PERSON1_UUID
    value: fca98e3b-ed7a-438d-b89f-2df2ee4a3bd9
  - name: SCHEDULING_WS_URL
    value: https://fm-tsv-scheduling-ws-dev.pvu.cf.churchofjesuschrist.org/api/v1
  - name: PERSON3_UUID
    value: fa2001bd-4836-499d-a434-ab8c77cf8c4f
  - name: PERSON2_UUID
    value: 79c771f0-579f-492e-a835-35c949a28fb3
  - name: PERSON5_UUID
    value: 08e57f98-7796-4518-934b-9d19cb6ea955
  - name: WORKER5_ID
    value: "9108"
  - name: PERSON4_UUID
    value: 5a449af6-a84f-4016-98e5-77d4017b8454
  - name: WORKER4_ID
    value: "9107"
